---
dependencies:
  - ivansible.lin_base

galaxy_info:
  role_name: lin_ferm
  author: "Ivan Andreev"
  description: "Setup FERM, frontend for iptables with ipset support"
  company: "IvanSible"
  license: MIT
  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic

  galaxy_tags:
    - linux
    - firewall
    - ferm

  github_branch: master
...
