---
provisioner:
  name: ansible
  inventory:
    group_vars:
      molecule:
        ansible_user: ansible
  config_options:
    defaults:
      strategy: linear
      verbosity: 1
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
    options:
      max-line-length: 120
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: focal
    groups:
      - molecule
    image: ivandeex/molecule:20.04
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: bionic
    groups:
      - molecule
    image: ivandeex/molecule:18.04
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
scenario:
  name: default
  converge_sequence:
    - converge
  test_sequence:
    - lint
    - dependency
    # - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    # - side_effect
    - verify
    # - cleanup
    - destroy
...
