---
provisioner:
  name: ansible
  inventory:
    group_vars:
      molecule:
  playbooks:
    prepare: ../default/prepare.yml
    converge: ../default/converge.yml
  config_options:
    defaults:
      strategy: linear
      verbosity: 1
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
    options:
      max-line-length: 120
  directory:
    ../default/tests
dependency:
  name: galaxy
  options:
    role-file: molecule/default/requirements.yml
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: localhost
    groups:
      - molecule
scenario:
  name: localhost
  test_sequence:
    - lint
    - dependency
    # - cleanup
    # - destroy
    - syntax
    # - create
    - prepare
    - converge
    - idempotence
    # - side_effect
    - verify
    # - cleanup
    # - destroy
...
