---
dependencies:
  - ivansible.lin_base  # for lin_firewall

galaxy_info:
  role_name: lin_yggdrasil
  author: "Ivan Andreev"
  description: "setup yggdrasil on linux"
  company: "IvanSible"
  license: MIT
  min_ansible_version: 2.5

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic

  galaxy_tags:
    - linux
    - yggdrasil
    - vpn

  github_branch: master
...
