---
name: Molecule test
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

env:
  ROLE_NAME: ivansible.lin_ssh
  ANSIBLE_FORCE_COLOR: true

jobs:
  localhost_test:
    name: test on host
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-16.04
          - ubuntu-18.04
    env:
      SCENARIO: localhost
      IVATEST_FIREWALL: ferm
      # disable ssh server on github runners
      IVATEST_SSH_SERVER: false
      IVATEST_SSH_PORT: 0

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          path: ivansible/${{ env.ROLE_NAME }}

      - name: Install requisites
        shell: bash
        run: |
          # stock and pypy flavors of PyYAML are incompatible:
          sudo apt-get remove -q -y python3-yaml
          sudo -H pip3 install -U pip setuptools wheel
          sudo -H pip3 install docker jmespath netaddr boto3 mitogen molecule pytest testinfra
          # also pulled: ansible-lint yamllint flake8

      - name: Run test
        shell: bash
        run: cd ivansible/$ROLE_NAME && molecule test -s $SCENARIO

  docker_test:
    name: tests in docker
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
    env:
      SCENARIO: default
      IVATEST_FIREWALL: none
      # perform ssh server test in docker
      IVATEST_SSH_SERVER: true
      IVATEST_SSH_PORT: 22

    steps:  # copy-pasting above steps since anchors are unsupported
      - name: Checkout
        uses: actions/checkout@master
        with:
          path: ivansible/${{ env.ROLE_NAME }}

      - name: Install requisites
        shell: bash
        run: |
          # stock and pypy flavors of PyYAML are incompatible:
          sudo apt-get remove -q -y python3-yaml
          sudo -H pip3 install -U pip setuptools wheel
          sudo -H pip3 install docker jmespath netaddr boto3 mitogen molecule pytest testinfra
          # also pulled: ansible-lint yamllint flake8

      - name: Run test
        shell: bash
        run: cd ivansible/$ROLE_NAME && molecule test -s $SCENARIO
...
