---
dependencies:
  - ivansible.lin_base

galaxy_info:
  role_name: lin_podman
  author: "Ivan Andreev"
  description: "install podman toolset on linux"
  company: "IvanSible"
  license: MIT
  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic

  galaxy_tags:
    - linux
    - ansible

  github_branch: master
...
